name: Angular CI

on:
  push:
    branches: [ '*' ]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build 
    - name: Run unit tests
      run: npm run test
    - name: List output directory contents
      run: ls -l
    - uses: actions/checkout@v2
    - name: Install Netlify CLI
      run: npm install netlify-cli -g
    - name: Deploy to Netlify
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: netlify deploy --prod --dir=dist/my-github/browser --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
